<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\StreamingProject.Application\StreamingProject.Application.csproj" />
      <ProjectReference Include="..\StreamingProject.Domain\StreamingProject.Domain.csproj" />
      <ProjectReference Include="..\StreamingProject.Infrastructure.Postgres\StreamingProject.Infrastructure.Postgres.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LiveStreamingServerNet" Version="0.33.1" />
      <PackageReference Include="LiveStreamingServerNet.Rtmp" Version="0.33.1" />
      <PackageReference Include="LiveStreamingServerNet.Rtmp.Server" Version="0.33.1" />
      <PackageReference Include="LiveStreamingServerNet.StreamProcessor.AspNetCore" Version="0.33.1" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    </ItemGroup>

</Project>
