<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
      <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\StreamingProject.Contracts\StreamingProject.Contracts.csproj" />
      <ProjectReference Include="..\StreamingProject.Domain\StreamingProject.Domain.csproj" />
    </ItemGroup>

</Project>
